# See https://upptime.js.org/docs/configuration for documentation
owner: woodcoin-core
repo: upptime

sites:
  - name: Woodcoin Explorer
    url: https://explorer.woodcoin.org/chain/Woodcoin
  - name: Woodcoin Site
    url: https://woodcoin.org
  - name: Woodcoin New Explorer
    url: https://new.explorer.woodcoin.org

assignees:
  - Lvl4Sword

status-website:
  logoUrl: https://raw.githubusercontent.com/woodcoin-core/media/main/logo/woodcoin128x128.png
  name: Woodcoin
  introTitle: Uptime stats
  introMessage: Stats for the woodcoin.org site, as well as explorer.woodcoin.org and new.explorer.woodcoin.org subdomains
  cname: status.woodcoin.org
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
